version: "3"

services:
    selenium:
        image: selenium/standalone-chrome
        ports:
        - 4444:4444
        restart: always
        privileged: true
        shm_size: 2g

    app:
        build: 
            context: .
        volumes: 
        - ./app:/app
        command: sh -c "python3 webscrap.py"
        depends_on:
         - selenium
  
